### ISSUE TITLE
CentOS7如何安装

### ISSUE THREAD

**Issue by liangjiongyao** [coslyk/moonplayer#66]
CentOS7不能使用fedora社区源，用源码的话要怎么装？

**Comment by coslyk** [comment]
https://github.com/coslyk/moonplayer/wiki/DownloadZH

**Comment by lowy** [comment]
centos7源码安装后无法解析视频

WARNING:downloader:failed to import ThreadPoolExecutor!
WARNING:downloader:multithread download disabled!
WARNING:downloader:please install concurrent.futures from https://github.com/agronholm/pythonfutures !
CRITICAL:YKDL:can't play this video!!
![Uploading 2018-11-03-21:37:28.png…]()
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
更新之后问题依旧 如此往复

**Comment by coslyk** [comment]
提供下视频地址？

**Comment by lowy** [comment]
就是普普通通的b站新番 同样的问题也出现在debian系统unblock b站跨区番剧上 比如佐贺勇者是传奇

**Comment by coslyk** [comment]
这种限港澳台的新番当然看不了 需要挂代理 ("▔㉨▔)

**Comment by lowy** [comment]
挂代理是自然的了 但是随便一个youtube视频就这样 是不是视频解析的部分没有走代理啊？ 能不能使用官方源里安装的youtube-dl?
![_moonplayer_20181107114214](https://user-images.githubusercontent.com/6565177/48110014-d4e2e480-e284-11e8-8d7e-fb51a6598612.png)

**Comment by coslyk** [comment]
ykdl不支持解析YouTube，you-get是可以解析的要看看代理设置，如果是unblockcn模式的话只会对中国大陆的视频网站解析走代理，其他模式是全局走代理
