### ISSUE TITLE
Offer AppImage release

### ISSUE THREAD

**Issue by baimafeima** [coslyk/moonplayer#68]
https://appimage.org/

**Comment by coslyk** [comment]
Hello @baimafeima 
The AppImage is already available in [Release](https://github.com/coslyk/moonplayer/releases) or [Download](https://github.com/coslyk/moonplayer/wiki/DownloadZH) pages. Please check them carefully before submitting an issue. Thanks!

After all I still recommend you to use the traditional way to install the program like Apt on Debian/Ubuntu or AUR on ArchLinux, because I cannot ensure that the AppImage works well with the hardware acceleration, which may lead to higher power consuming.

**Comment by baimafeima** [comment]
@coslyk Apologies, I must have overlooked the AppImage file. Will check it out now.
