### ISSUE TITLE
Bundle plugins in AppImage

### ISSUE THREAD

**Issue by probonopd** [coslyk/moonplayer#79]
Thank you for providing an AppImage. First thing it shows is:

![](https://github.com/AppImage/appimage.github.io/blob/55813059fc199c48dff1c7ce0a144d65f6ef1fa5/database/MoonPlayer/screenshot.png?raw=true)

Would it be possible to bundle all the plugins inside the AppImage, so that the user does not have to separately download them?

Thanks.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1582

**Comment by coslyk** [comment]
MoonPlayer uses [Youtube-dl](https://github.com/ytdl-org/youtube-dl) and [ykdl](https://github.com/zhangn1985/ykdl) to parse videos from websites, which update very frequently, so I think it's better to make them seperate so that it's easier to get the latest version of them using a built-in upgrader.

**Comment by probonopd** [comment]
I see.
